/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/host": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get host identity and version. */
        get: operations["getHostInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List virtual machines on the host. */
        get: operations["listVms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vms/{vmId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Hyper-V virtual machine ID. */
                vmId: components["parameters"]["VmId"];
            };
            cookie?: never;
        };
        /** Get a single virtual machine. */
        get: operations["getVm"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vms/{vmId}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Hyper-V virtual machine ID. */
                vmId: components["parameters"]["VmId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a power action on a virtual machine.
         * @description Starts an asynchronous state change. Poll `GET /vms/{vmId}` (the `Location`
         *     header) to observe the resulting state.
         *
         *     `turnOff` is equivalent to pulling the power cord and can lose unsaved data
         *     in the guest. Clients must confirm with the user before sending it.
         */
        post: operations["performVmAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vms/{vmId}/provision": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Hyper-V virtual machine ID. */
                vmId: components["parameters"]["VmId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create the calling User's local account in a VM.
         * @description One-time setup for one-click Remote Desktop. Uses PowerShell Direct with the given
         *     guest administrator credential to create (or reuse) the User's local account, for
         *     example `hh-owner`, add it to Remote Desktop Users, and optionally enable Remote
         *     Desktop. The VM is marked provisioned only after the account is verified. Requires a
         *     running Windows guest (Windows 10 / Server 2016 or later).
         */
        post: operations["provisionVm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vms/{vmId}/connect": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Hyper-V virtual machine ID. */
                vmId: components["parameters"]["VmId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Remote Desktop credentials for the calling User's account.
         * @description Rotates the User's account password in the guest through PowerShell Direct and
         *     returns it. Rotations are serialized per VM and User; requests within the reuse
         *     window (60 seconds by default) receive the same password. The response is sent
         *     with `Cache-Control: no-store`.
         */
        post: operations["connectVm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pairing/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Begin pairing and display a PIN on the host. */
        post: operations["createPairingRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pairing/requests/{pairingId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pairingId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Cancel a pending pairing request.
         * @description Ends the request and closes the PIN window on the host. The pairing ID is only
         *     known to the client that created the request.
         */
        delete: operations["cancelPairingRequest"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pairing/requests/{pairingId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pairingId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Prove knowledge of the PIN and complete pairing. */
        post: operations["confirmPairing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pairing/devices/self": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove the calling device's pairing.
         * @description Revokes the client certificate used for this request.
         */
        delete: operations["unpairSelf"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wake/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get network adapter details needed to wake the host. */
        get: operations["getWakeInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wake/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check whether the host is configured to wake on LAN. */
        get: operations["getWakeReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wake/readiness/fix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply automatic fixes for failed readiness checks.
         * @description Fixes change system settings and need administrator rights. When the host service
         *     has them, the fixes are applied immediately (200). Otherwise the host tray asks the
         *     user to approve them with a UAC prompt (202); poll `GET /wake/readiness` to see the
         *     result. Only checks with `autoFixAvailable` can be fixed.
         */
        post: operations["fixWakeReadiness"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wake/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Put the host to sleep after a delay so the client can test waking it. */
        post: operations["startWakeTest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 7807 problem details. */
        ProblemDetails: {
            type?: string;
            title?: string;
            status?: number;
            detail?: string;
            instance?: string;
        };
        /**
         * @example {
         *       "hostId": "6f1c2b8e-3a4d-4c55-9e1f-2b7a9d0c4e11",
         *       "hostName": "GAMING-PC",
         *       "version": "0.1.0",
         *       "apiVersion": "1.0.0",
         *       "certificateFingerprint": "3F2A9C1D4B5E6F708192A3B4C5D6E7F8091A2B3C4D5E6F708192A3B4C5D6E7F8"
         *     }
         */
        HostInfo: {
            /**
             * Format: uuid
             * @description Stable identifier generated at first run.
             */
            hostId: string;
            /** @description Windows computer name. */
            hostName: string;
            /** @description Host service version. */
            version: string;
            /** @description Contract version implemented by the host. */
            apiVersion: string;
            /** @description SHA-256 fingerprint of the host TLS certificate, uppercase hex. */
            certificateFingerprint: string;
        };
        /** @enum {string} */
        VmState: "running" | "off" | "saved" | "paused" | "starting" | "stopping" | "saving" | "pausing" | "resuming" | "other";
        /**
         * @description - `start`: power on or resume from saved state.
         *     - `shutdown`: graceful guest shutdown via integration services.
         *     - `turnOff`: immediate power off. Can lose unsaved guest data.
         *     - `save`: save memory state to disk and stop.
         *     - `restart`: graceful guest restart.
         * @enum {string}
         */
        VmAction: "start" | "shutdown" | "turnOff" | "save" | "restart";
        /**
         * @example {
         *       "id": "0b9a6f53-1c2d-4e8f-a1b2-3c4d5e6f7a8b",
         *       "name": "Dev Workstation",
         *       "state": "running",
         *       "uptimeSeconds": 3600,
         *       "cpuUsagePercent": 12,
         *       "memoryAssignedMb": 8192,
         *       "generation": 2,
         *       "rdpAvailable": true,
         *       "ipAddresses": [
         *         "192.168.1.50"
         *       ],
         *       "provisioned": true,
         *       "remoteDesktop": {
         *         "address": "192.168.1.50",
         *         "reachableFromHost": true
         *       }
         *     }
         */
        Vm: {
            /**
             * Format: uuid
             * @description Hyper-V virtual machine ID.
             */
            id: string;
            name: string;
            state: components["schemas"]["VmState"];
            /** Format: int64 */
            uptimeSeconds?: number;
            cpuUsagePercent?: number | null;
            /** Format: int64 */
            memoryAssignedMb?: number | null;
            /** @enum {integer} */
            generation: 1 | 2;
            /**
             * @description True when the VM accepted a TCP connection on port 3389 from the host. A VM on an
             *     internal or NAT switch can be available to the host but unreachable from other devices.
             */
            rdpAvailable: boolean;
            ipAddresses: string[];
            /**
             * @description True when the calling device's User has a verified local account on this VM, so
             *     `POST /vms/{vmId}/connect` can be used.
             */
            provisioned: boolean;
            remoteDesktop: components["schemas"]["VmRemoteDesktop"];
        };
        VmRemoteDesktop: {
            /** @description The guest address clients connect to, or null when the guest reports none. */
            address: string | null;
            /** @description Same as Vm.rdpAvailable. */
            reachableFromHost: boolean;
        };
        ProvisionVmRequest: {
            /** @description A local administrator in the guest, for example "Administrator" or ".\\admin". */
            adminUserName: string;
            /** @description Stored on the host with DPAPI for later password rotation. Never logged. */
            adminPassword: string;
            /**
             * @description Also enable Remote Desktop and its firewall rule in the guest.
             * @default true
             */
            enableRemoteDesktop: boolean;
        };
        VmProvisioning: {
            /** Format: uuid */
            vmId: string;
            /** @description The User's local account in the guest, for example hh-owner. */
            accountName: string;
            /** Format: date-time */
            provisionedAt: string;
        };
        VmConnection: {
            /** @description Account to sign in with, for example ".\\hh-owner". */
            userName: string;
            /**
             * @description Current password for the account. Valid until the next rotation; requests within
             *     the reuse window receive the same password. Clients must not persist it.
             */
            password: string;
            address: string;
            /** @default 3389 */
            port: number;
            /**
             * Format: date-time
             * @description End of the reuse window. The password stays valid until the next connect after it.
             */
            expiresAt: string;
        };
        VmActionRequest: {
            action: components["schemas"]["VmAction"];
        };
        /**
         * @example {
         *       "vmId": "0b9a6f53-1c2d-4e8f-a1b2-3c4d5e6f7a8b",
         *       "action": "turnOff",
         *       "accepted": true,
         *       "state": "stopping"
         *     }
         */
        VmActionResult: {
            /** Format: uuid */
            vmId: string;
            action: components["schemas"]["VmAction"];
            accepted: boolean;
            state: components["schemas"]["VmState"];
        };
        PairingRequest: {
            /** @description Name shown in the host tray. */
            deviceName: string;
            /** @description PEM-encoded self-signed client certificate. */
            clientCertificatePem: string;
        };
        PairingRequestCreated: {
            /** Format: uuid */
            pairingId: string;
            /**
             * Format: byte
             * @description SPAKE2 share Y, 384 bytes big-endian, Base64 encoded.
             */
            hostShare: string;
            /** Format: date-time */
            expiresAt: string;
        };
        PairingConfirmation: {
            /**
             * Format: byte
             * @description SPAKE2 share X, 384 bytes big-endian, Base64 encoded.
             */
            clientShare: string;
            /**
             * Format: byte
             * @description Confirmation cA (HMAC-SHA256), Base64 encoded.
             */
            clientConfirmation: string;
        };
        PairingResult: {
            /** Format: uuid */
            deviceId: string;
            /**
             * Format: uuid
             * @description The User the new device belongs to. A User owns many devices and has one local
             *     account on each provisioned VM.
             */
            userId: string;
            /** Format: uuid */
            hostId: string;
            /** @description PEM-encoded host certificate to pin. */
            hostCertificatePem: string;
            /**
             * Format: byte
             * @description Confirmation cB (HMAC-SHA256), Base64 encoded.
             */
            hostConfirmation: string;
        };
        WakeAdapter: {
            name: string;
            macAddress: string;
            /** Format: ipv4 */
            ipv4Address: string;
            /** Format: ipv4 */
            broadcastAddress: string;
        };
        /**
         * @example {
         *       "adapters": [
         *         {
         *           "name": "Ethernet",
         *           "macAddress": "00-1A-2B-3C-4D-5E",
         *           "ipv4Address": "192.168.1.10",
         *           "broadcastAddress": "192.168.1.255"
         *         }
         *       ]
         *     }
         */
        WakeInfo: {
            adapters: components["schemas"]["WakeAdapter"][];
        };
        /** @enum {string} */
        WakeCheckStatus: "pass" | "warn" | "fail";
        WakeCheck: {
            /**
             * @description Stable check identifier: `wiredAdapter`, `nicWakeOnMagicPacket`,
             *     `nicAllowWake`, `sleepKeepsNetwork`, or `fastStartupDisabled`. Clients should
             *     show unknown identifiers using `title` and `detail`.
             */
            id: string;
            title: string;
            status: components["schemas"]["WakeCheckStatus"];
            detail?: string;
            autoFixAvailable: boolean;
        };
        /**
         * @example {
         *       "ready": false,
         *       "checks": [
         *         {
         *           "id": "nicWakeOnMagicPacket",
         *           "title": "Network adapter wakes on magic packet",
         *           "status": "fail",
         *           "detail": "Wake on Magic Packet is disabled on adapter Ethernet.",
         *           "autoFixAvailable": true
         *         }
         *       ]
         *     }
         */
        WakeReadiness: {
            /** @description True when no check has status `fail`. */
            ready: boolean;
            checks: components["schemas"]["WakeCheck"][];
        };
        WakeFixRequest: {
            checkIds: string[];
        };
        WakeTestRequest: {
            delaySeconds: number;
        };
        WakeTestScheduled: {
            /** Format: date-time */
            sleepAt: string;
        };
    };
    responses: {
        /** @description The request was malformed or failed validation. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description The client certificate is missing or not paired with this host. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description The resource does not exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description The operation is not valid in the current state. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Hyper-V rejected the request with an unexpected return code. */
        HyperVOperationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description A PowerShell Direct operation in the guest failed. */
        GuestOperationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description The guest is not ready for PowerShell Direct (still starting, or integration services are off). */
        GuestUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Hyper-V is not enabled or the host service cannot access it. */
        HyperVUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Another pairing request is already pending. */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        /** @description Hyper-V virtual machine ID. */
        VmId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHostInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Host information. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostInfo"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listVms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All virtual machines visible to the host service. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vm"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["HyperVUnavailable"];
        };
    };
    getVm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Hyper-V virtual machine ID. */
                vmId: components["parameters"]["VmId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The virtual machine. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vm"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["HyperVUnavailable"];
        };
    };
    performVmAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Hyper-V virtual machine ID. */
                vmId: components["parameters"]["VmId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "action": "start"
                 *     }
                 */
                "application/json": components["schemas"]["VmActionRequest"];
            };
        };
        responses: {
            /** @description The action was accepted. */
            202: {
                headers: {
                    /** @description URL of the virtual machine resource. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VmActionResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            502: components["responses"]["HyperVOperationFailed"];
            503: components["responses"]["HyperVUnavailable"];
        };
    };
    provisionVm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Hyper-V virtual machine ID. */
                vmId: components["parameters"]["VmId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProvisionVmRequest"];
            };
        };
        responses: {
            /** @description The account exists and was verified. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VmProvisioning"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description The VM is not running, is not a Windows guest, or an existing account with the same name is not a local account. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The guest rejected the administrator credential. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            502: components["responses"]["GuestOperationFailed"];
            503: components["responses"]["GuestUnavailable"];
        };
    };
    connectVm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Hyper-V virtual machine ID. */
                vmId: components["parameters"]["VmId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Credentials for Remote Desktop. */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VmConnection"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description The VM is not provisioned for this User, is not running, or has no address. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            502: components["responses"]["GuestOperationFailed"];
            503: components["responses"]["GuestUnavailable"];
        };
    };
    createPairingRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairingRequest"];
            };
        };
        responses: {
            /** @description Pairing request created; the PIN is shown in the host tray. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairingRequestCreated"];
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
            /** @description No tray app is connected to show the PIN. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    cancelPairingRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pairingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was cancelled. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    confirmPairing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pairingId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairingConfirmation"];
            };
        };
        responses: {
            /** @description Pairing completed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairingResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description The confirmation did not match; the PIN was wrong or the exchange was tampered with. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description The pairing request expired or the attempt limit was reached. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    unpairSelf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The device was unpaired. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getWakeInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wake-capable adapters. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WakeInfo"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getWakeReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Readiness check results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WakeReadiness"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    fixWakeReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WakeFixRequest"];
            };
        };
        responses: {
            /** @description Readiness check results after applying fixes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WakeReadiness"];
                };
            };
            /** @description The user at the host has been asked to approve the fixes. */
            202: {
                headers: {
                    /** @description URL of the readiness resource to poll. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Approval is needed and no tray app is running on the host to ask. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    startWakeTest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WakeTestRequest"];
            };
        };
        responses: {
            /** @description The host will sleep at the indicated time. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WakeTestScheduled"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
        };
    };
}
